- Nicolas_Fierro_Viedma.txt
> Nicolas_Fierro_Viedma

- Cualquier cosa Javi Ramirez.txt
primer archivo :P Primera semana
> Javi Ramirez

- Benja_Gutierrez.txt
> benja_gutierrez

- Elena.Errazuriz.rtf
Tarea 1, prueba de pula request
> Elena Errazuriz

- Gabriela Navarro.rtf
> Gabi Navarro

- anamaria.txt
> la tarea 01

- s01e01catajuez/s01e01catalina/s01e01catalina.pde
- s01e01catajuez/s01e02catalina/s01e02catalina.pde
Ejercicios de la primera clase (copiar dos imagines usando variables)
> s01e01catajuez

- s01e01pancho/s01e01pancho.pde
- s01e02pancho/s01e02pancho.pde
> s01e01pancho + s01e02pancho

- Untitled.txt
- s01e01benja/s01e01benja.pde
- s01e02/s01e02.pde
- s01e02benja/s01e02benja.pde
> s01e01benja

- .gitignore
- s01e01max/s01e01max.pde
- s01e02max/s01e02max.pde
Copiar los 4 elementos entregados por Nicotron usando variables, rect,
line y ellipse.
> s01e01-2max

- s01e00cringelings/s01e00cringelings.pde
- s01e01cringelings/s01e01cringelings.pde
> s01e00cringelings + s01e01cringelings

- s01e01elenaerrazuriz/s01e01elenaerrazuriz.pde
- s01e01elenaerrazuriz_2/s01e01elenaerrazuriz_2.pde
> s01e01elenaerrazuriz

- s01e01elenaerrazuriz_corregido/s01e01elenaerrazuriz_corregido.pde
- s01t01elenaerrazuriz/s01t01elenaerrazuriz.pde
tarea 1 más la corrección del ejercicio de la clase pasada
> s01t01elenaerrazuriz

- s01t01anamaria.pde
- s01t01anamaria/s01t01anamaria.pde
Tarea de figuras y colores. Linea blanca, circulo calipso y borde blanco, cuadrado amarillo y punto
negro.
> s01t01anamaria

- tareas/s01t01Dante/s01t01Dante.pde
Trabajo dos colores de elección propia mas blanco y negro. Dante
> s01t01Dante

- s02t01cringelings./s02t01cringelings.pde
- s02t01cringelings/s02t01cringelings.pde
> Tarea Nº1 cringelings

- s02t01elenaerrazuriz/s02t01elenaerrazuriz.pde
tarea semana 2, pattern con función for
> s02t01elenaerrazuriz

- s04c00Javiera/s04c00Javiera.pde
- s04c01Javiera/s04c01Javiera.pde
El patrón del archivo s04c00Javiera corresponde al póster y el patrón
del archivo s04c01Javiera corresponde al de la libreta
> s04c00Javiera - s04c01Javiera

- s04t00elenaerrazuriz/s04t00elenaerrazuriz.pde
> s04t00elenaerrazuriz

- s04t00Javiera/s04t00Javiera.pde
> s04t00Javiera

- s04t00margaux/s04t00margaux.pde
grilla de filas (9x7) de elipses
> s04t00margaux

- s05t00Javiera/s05t00Javiera.pde
- s06e00Javiera/s06e00Javiera.pde
- s06e01Javiera/s06e01Javiera.pde
> s05t00Javiera

- s05t00maite/s05t00maite.pde
- s06e01maite/s06e01maite.pde
- s06e02maite/s06e02maite.pde
Tarea semana 05
Marte Iturriaga
> s05t00maite

- s05t00anamaria/s05t00anamaria.pde
> s05t00anamaria

- s05t00elenaerrazuriz/s05t00elenaerrazuriz.pde
- s06e00elenaerrazuriz/s06e00elenaerrazuriz.pde
- s06e01elenaerrazuriz/s06e01elenaerrazuriz.pde
> s05t00elenaerrazuriz

- s06eanamaria/s06e00anamaria.pde
- s06eanamaria/s06e01anamaria.pde
- s06t00anamaria/s06t00anamaria.pde
Ejercicios y tarea:
s06e00anamaria 
s06e01anamaria
s06t00anamaria
> S06anamaria

- s06t00elenaerrazuriz/s06t00elenaerrazuriz.pde
- s07e00elenaerrazuriz/Objeto.pde
- s07e00elenaerrazuriz/s07e00elenaerrazuriz.pde
- s07t00elenaerrazuriz/Objeto.pde
- s07t00elenaerrazuriz/s07t00elenaerrazuriz.pde
> s06t00elenaerrazuriz

- s06t00Javiera/s06t00Javiera.pde
- s07e00Javiera/Class.pde
- s07e00Javiera/s07e00Javiera.pde
> s06t00Javiera

- s06t00Benja/s06t00Benja.pde
- s07t00Benja/Object.pde
- s07t00Benja/s07t00Benja.pde
> tarea semana 06

- s06t00maite/s06t00maite.pde
> s06t00maite

- s07e00cringelings/Objeto.pde
- s07e00cringelings/s07e00cringelings.pde
- s07e01cringelings/Objeto.pde
- s07e01cringelings/s07e01cringelings.pde
- s07t00cringelings/Objeto.pde
- s07t00cringelings/s07t00cringelings.pde
- s08e00cringelings/s08e00cringelings.pde
- s08e01cringelings/Objeto.pde
- s08e01cringelings/s08e01cringelings.pde
- s08t00cringelings/Objeto.pde
- s08t00cringelings/s08t00cringelings.pde
Todos los trabajos que no había mandado por resetear el computador.
> s08e00cringelings

- s10c01elenaerrazuriz/Elena.pde
- s10c01elenaerrazuriz/s10c01elenaerrazuriz.pde
> s10c01elenaerrazuriz

- s10c01anamaria/Objeto.pde
- s10c01anamaria/s10c01anamaria.pde
> s10c01anamaria

- s10c01dante/Objects.pde
- s10c01dante/s10c01dante.pde
> s10c01dante

- s10c01CatalinaJuez/Objeto.pde
- s10c01CatalinaJuez/Objeto2.pde
- s10c01CatalinaJuez/s10c01CatalinaJuez.pde
> s10c01CatalinaJuez

- s10c01Benja/Body.pde
- s10c01Benja/s10c01Benja.pde
segundo certamen del semestre, no logre crear mas de una grilla y
entender como lo hice por lo que solo entrego la clase con su
respectiva función
> certamen 01

- s10c01/s10c01.pde
> s10c01pancho

- s10c01_v2/Objeto.pde
- s10c01_v2/s10c01_v2.pde
> s10c01v2pancho
